### ISSUE TITLE
How to verify the correctness of two implementations of yinyang k-means?

### ISSUE THREAD

**Issue by zty2developer** [ctaylor389/k_means_yinyang_gpu#2]
Hello, I cloned your repository and made some changes on **yinyang k-means on cpu**.

**So I want to verify if my new algorithm is right. Could you please tell me how you guys determinate if your algorithm is right?**

For example: how do you know your SIMPLECPU algorithm is right as your SUPERCPU algorithm?

I tried to compare the result of my new algorithm with yours in the following aspect, but I'm still not sure if my algorithm is correct: 

1. **final position of centers:** I've tried comparing the final position of centers of two algorithms.But it seems with the increase of K, the error of position of centers becomes bigger. In my opinion, the reason is that float addition in centroid updating stage brings a loss of precision(I use 32-bit float instead of double). So the comparison of center's final position has few effect on the judgement of correctness, is that right?

2. **the number of iterations:** my new algorithm inherit the idea of yinyang k-means, so the number of iterations will not change. Thus I think the clustering result of my new algorithm is right if the number of iterations of two algorithm is approximate. is that right?

3. **final point assignment:** I think it is normal that my new algorithm's final point assignments is not completely the same as yours. So final point assignment cannot be a effective evidence to prove the correctness of my algorithm.

Thank you very much if you can give me some advise.

**Comment by ctaylor389** [comment]
Sorry for the late reply. I haven't logged onto my personal github in a while. 

1: Yes, we came to the same conclusion. How I personally used to check correctness was via double precision comparisons to the naive version of the algorithm, as Yinyang only eliminates unnecessary distance calculations. As you theorized, it is very likely the floating point error caused via atomic adds during the centroid calculation phase. At double precision, this floating point error is much less noticeable.

2: Assuming the same convergence condition, and the algorithm is an exact k-means algorithm, you should expect the same number of iterations. For this gpu implementation at 32bit precision, this may not occur do to the atomic sums. 

3: Final point assignments are usually the easiest to get right in my experience, but like I said, I would recommend using double precision for any check of correctness.

Let me know if you have any other questions!

**Comment by zty2developer** [comment]
much appreciate!
